### ISSUE TITLE
Change style of recommended info

### ISSUE THREAD

**Issue by verde79** [GlasgowCoderCollective/resources#111]
I'd like all the divs that have are recommended by someone, in the code like 
<p>Recommended by
        <a class="recommended" href="https://github.com/dwmedina">Daniel Medina</a></p><p> in the United States (near Cleveland, Ohio)</p>
 
To display all the information on one line, so:
Recommended by Daniel Medina in the United States (near Cleveland, Ohio)

I'd like all the divs that have a recommended by section fixed to appear on one line instead of two

Only submit these changes in a PR, nothing additonal

**Comment by dadams89** [comment]
Taking this!

**Comment by verde79** [comment]
Thanks @dadams89
