### ISSUE TITLE
readme code needs styled

### ISSUE THREAD

**Issue by verde79** [GlasgowCoderCollective/resources#3]
The instructions in the readme file are rather boring looking and the code sections ie git clone.....
could do with having markdown to style them like
`git fetch origin master`

open for anyone to do, just assign yourself if interested

**Comment by JoelLau** [comment]
hi @verde79, I would love to help out. Lmk what I can do

**Comment by verde79** [comment]
If you could style the sections with git instructions ie git add upstream, git clone ...

An example of how to do this: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code.  just have to put apostrophes(aka backticks) round the git commands

**Comment by JoelLau** [comment]
sounds like something I could do, I'll make a Pull Request as soon as I'm done 😄
